language: go
go:
    - 1.7
sudo: required
services:
    - docker
before_install:
    - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - sudo add-apt-repository -y ppa:masterminds/glide
    - sudo apt-get -qq update
    - sudo apt-get -y install glide nodejs tree
    - npm install webpack -g
    - go get github.com/vektra/mockery/.../
    - glide -version
    - node -v
    - npm -v
install:
    - glide up
    - pushd $TRAVIS_BUILD_DIR/sample/authkit/ui-web && npm install && popd
script:
    - tree -df -L 3 vendor
    - make
    - pushd $TRAVIS_BUILD_DIR/sample/authkit/ && make up down ARGS="-dbg" && popd
notifications:
    email: false
    slack:
        rooms:
            secure: nxhQLof0eEJB3S2EKeq+zmO6O1j4xD5aRbDrJ2p52UXvIV+EFf8XG37JiitTylV/hzXSi4zRym54XX48G+4cWOVEdBxdP9xiilsvm6Wa7zuokz+uLCFeAEqMT34M4zF9BgWNipcu8U2J5FU2sp3XkGqje3PWw2Fv6MqZ1l3YWkK6nC8H6WJJ+9jqp0DCMUTYKoCKdl/aSDOdKZZzm6UFY+Iu2dWS9gqQchjRIoBwzDKa2APuSLaW87VTGkuiEHX3kBlcWTbJKOYxEng53/K6d7bmCvVKaNLj6SbmHDzDM6l9qyDIdrEE5WGZYBCFk0k6vYxQIvHwpwO53Azn0y86D8LskxfVnUAGXk6q9HML8PglnwozD+YE/SuA67F8CuTZYpGzca0nd+GGRmrYE4qInGuYeO4X+d3FhQ3uNENNnh8TUR/CN4mBDriRCWHWnedFNr0z+mPWl12uRn1p5KnLOdnoJTzu0fCcNxwYPFGi4M7ou6WBMh/C9Jy4R7ngtM5ZkE3M0rF3f5Gui0egcJTttI9PtYzXu1UNmooR0pTnwUaKth+3Tcj8D/un9Va6qSshLyRnAgynBPuIgCwoEw+VcTYpWVgqBiQS82PoryjbgS03jNJCyC0mdkY8ITz7hvV2EAb0vY5i4pnbB0PG5UNU+LwqktWUkYx9E1aoV+u0TBA=
