#!/bin/bash

# This script updates Hydra API spec from github
# and patches it to generate less ugly package and method names.

APISRC='https://gist.githubusercontent.com/nikolay-turpitko/472213904f324ef89cb27a9225adb142/raw/20a9f13bb8722599c602879ae921e0dc8506f7b5/hydra.yaml'

# Download spec.
echo "Download apib spec..."
wget -O hydra.yaml "$APISRC"

# Fix spec.
patch -i hydra.authkit.patch -o hydra.authkit.yaml hydra.yaml

# Remove intermediate file.
#rm hydra.yaml
