import './views/navbar.html'
import './views/error-msg.html'
import './views/auth.html'
import './views/dlg-login.html'
import './views/login-provider.html'
import './views/profile.html'
import './views/app.html'
